/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package deduplicatorGUI.layouts;

/**
 *
 * @author duck
 */
public class ScheduleJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ScheduleJPanel
     */
    public ScheduleJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        typeButtonGroup = new javax.swing.ButtonGroup();
        dayButtonGroup = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        dateTextField = new javax.swing.JFormattedTextField();
        timeSpinner = new javax.swing.JSpinner();
        oneOffRadioButton = new javax.swing.JRadioButton();
        dailyRadioButton = new javax.swing.JRadioButton();
        weeklyRadioButton = new javax.swing.JRadioButton();
        monthlyradioButton = new javax.swing.JRadioButton();
        mondayRadioButton = new javax.swing.JRadioButton();
        tuesdayRadioButton = new javax.swing.JRadioButton();
        wednesdayRadioButton = new javax.swing.JRadioButton();
        thursdayRadioButton = new javax.swing.JRadioButton();
        fridayRadioButton = new javax.swing.JRadioButton();
        saturdayRadioButton = new javax.swing.JRadioButton();
        sundayRadioButton = new javax.swing.JRadioButton();

        jLabel1.setText("Plan new scan:");

        jLabel2.setText("Scan start:");

        dateTextField.setText("date");
        dateTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateTextFieldActionPerformed(evt);
            }
        });

        oneOffRadioButton.setText("One off");
        oneOffRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oneOffRadioButtonActionPerformed(evt);
            }
        });

        dailyRadioButton.setText("Daily");

        weeklyRadioButton.setText("Weekly");

        monthlyradioButton.setText("Monthly");

        mondayRadioButton.setText("Monday");
        mondayRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mondayRadioButtonActionPerformed(evt);
            }
        });

        tuesdayRadioButton.setText("Tuesday");

        wednesdayRadioButton.setText("Wednesday");

        thursdayRadioButton.setText("Thursday");

        fridayRadioButton.setText("Friday");
        fridayRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fridayRadioButtonActionPerformed(evt);
            }
        });

        saturdayRadioButton.setText("Saturday");

        sundayRadioButton.setText("Sunday");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2)
                            .addComponent(dateTextField))
                        .addGap(18, 18, 18)
                        .addComponent(timeSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(mondayRadioButton)
                            .addComponent(tuesdayRadioButton)
                            .addComponent(wednesdayRadioButton))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(thursdayRadioButton)
                                .addComponent(saturdayRadioButton)
                                .addComponent(fridayRadioButton)
                                .addComponent(sundayRadioButton))
                            .addGap(16, 16, 16))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 109, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(monthlyradioButton)
                    .addComponent(weeklyRadioButton)
                    .addComponent(dailyRadioButton)
                    .addComponent(oneOffRadioButton))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(timeSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(oneOffRadioButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(dailyRadioButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(weeklyRadioButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(monthlyradioButton)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(mondayRadioButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tuesdayRadioButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(wednesdayRadioButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(thursdayRadioButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fridayRadioButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(saturdayRadioButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(sundayRadioButton))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void dateTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dateTextFieldActionPerformed

    private void oneOffRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oneOffRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_oneOffRadioButtonActionPerformed

    private void mondayRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mondayRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mondayRadioButtonActionPerformed

    private void fridayRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fridayRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fridayRadioButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton dailyRadioButton;
    private javax.swing.JFormattedTextField dateTextField;
    private javax.swing.ButtonGroup dayButtonGroup;
    private javax.swing.JRadioButton fridayRadioButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JRadioButton mondayRadioButton;
    private javax.swing.JRadioButton monthlyradioButton;
    private javax.swing.JRadioButton oneOffRadioButton;
    private javax.swing.JRadioButton saturdayRadioButton;
    private javax.swing.JRadioButton sundayRadioButton;
    private javax.swing.JRadioButton thursdayRadioButton;
    private javax.swing.JSpinner timeSpinner;
    private javax.swing.JRadioButton tuesdayRadioButton;
    private javax.swing.ButtonGroup typeButtonGroup;
    private javax.swing.JRadioButton wednesdayRadioButton;
    private javax.swing.JRadioButton weeklyRadioButton;
    // End of variables declaration//GEN-END:variables
}
